// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFLFantasyAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NFLFantasyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108025848_Sprint1_CompleteTables6")]
    partial class Sprint1_CompleteTables6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NFLFantasyAPI.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Liga")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("equipos", (string)null);
                });

            modelBuilder.Entity("NFLFantasyAPI.Models.EquipoLiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsComisionado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaUnion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<int>("IdLiga")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdLiga");

                    b.HasIndex("IdEquipo", "IdLiga")
                        .IsUnique();

                    b.ToTable("equipos_ligas", (string)null);
                });

            modelBuilder.Entity("NFLFantasyAPI.Models.Liga", b =>
                {
                    b.Property<int>("IdLiga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLiga"));

                    b.Property<int?>("ComisionadoId")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigPlayoffs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CuposOcupados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("CuposTotales")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("EsquemaPuntos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pre-Draft");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLimiteIntercambios")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormatoPosiciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdComisionado")
                        .HasColumnType("integer");

                    b.Property<int>("IdTemporada")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("LimiteMaximoCambios")
                        .HasColumnType("integer");

                    b.Property<int?>("LimiteMaximoContrataciones")
                        .HasColumnType("integer");

                    b.Property<string>("NombreLiga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("PermitirDecimales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("TemporadaId")
                        .HasColumnType("integer");

                    b.HasKey("IdLiga");

                    b.HasIndex("ComisionadoId");

                    b.HasIndex("IdComisionado");

                    b.HasIndex("IdTemporada");

                    b.HasIndex("NombreLiga");

                    b.HasIndex("TemporadaId");

                    b.ToTable("ligas", (string)null);
                });

            modelBuilder.Entity("NFLFantasyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activa");

                    b.Property<DateTime?>("FechaBloqueo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimoIntentoFallido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntentosFailidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UltimaActividad")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Semana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TemporadaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId");

                    b.ToTable("semanas", (string)null);
                });

            modelBuilder.Entity("Temporada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Nombre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("temporadas", (string)null);
                });

            modelBuilder.Entity("NFLFantasyAPI.Models.Equipo", b =>
                {
                    b.HasOne("NFLFantasyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NFLFantasyAPI.Models.EquipoLiga", b =>
                {
                    b.HasOne("NFLFantasyAPI.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyAPI.Models.Liga", "Liga")
                        .WithMany()
                        .HasForeignKey("IdLiga")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("NFLFantasyAPI.Models.Liga", b =>
                {
                    b.HasOne("NFLFantasyAPI.Models.Usuario", "Comisionado")
                        .WithMany()
                        .HasForeignKey("ComisionadoId");

                    b.HasOne("NFLFantasyAPI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdComisionado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Temporada", null)
                        .WithMany()
                        .HasForeignKey("IdTemporada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId");

                    b.Navigation("Comisionado");

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("Semana", b =>
                {
                    b.HasOne("Temporada", "Temporada")
                        .WithMany("Semanas")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("Temporada", b =>
                {
                    b.Navigation("Semanas");
                });
#pragma warning restore 612, 618
        }
    }
}
